// AUTO-GENERATED by tools/gen_palettes.py from tools/palettes/palettes.json.
// DO NOT EDIT. Edit palettes.json and re-run the generator.
//
// Each palette is FOUR explicit ring colors: [outer, middle, inner, center].
// Rendered SOLID per ring (like the "Clock colors" default, which paints each
// ring in one configured face color), NOT swept as a gradient, so structural
// accents land on their own ring instead of drowning in a one-hue sweep.
//
// SIMPLIFIED v2.27.0: ONE shared mood list drives BOTH chimes (animationPalette)
// and reminders (reminderPalette). "Clock colors" (index 7) is NOT here: the
// firmware intercepts it and ring-maps the user's configured face colors; it is
// the default. Removed flower palettes are archived in
// docs/archive/flower_palettes_2026-07-14.md.
//
// GAMMA: these values route through gammaColor() (gamma 2.2) at render time, so
// they are authored gamma-aware (inverse-gamma of the intended on-strip look).
#pragma once
#include <stdint.h>

constexpr uint8_t MOOD_PALETTE_COUNT = 4;

static const uint8_t MOOD_PALETTE_RINGS[4][4][3] = {
  // 0: Golden hour (warm): late-sun amber - the default warm mood, deep rim to bright core
  {{228,116,59}, {246,170,72}, {255,209,89}, {255,236,110}},
  // 1: Moonlight (cool): night-bloom white-violet - the coolest, quietest mood (renamed from 'Moonflower' - collided with the clock THEME name)
  {{174,96,228}, {155,146,241}, {122,194,243}, {151,236,246}},
  // 2: Dawn (soft-warm): sunrise rose to peach - a soft warm swell (re-authored from the old 'blush')
  {{231,96,163}, {248,146,132}, {255,194,122}, {255,226,142}},
  // 3: Twilight (muted-cool): dusk blue-violet - calm, muted, cool (re-authored from the old 'calm')
  {{127,110,209}, {110,159,223}, {103,203,218}, {142,236,220}},
};
